INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(1,Dessines-moi,47 boulevard Xavier Mahe        ,0571640714,56,Quimper,Finistère,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(2,Creation en tout genre,,0517889688,60,Brest,Finistère,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(3,Pick and mix,,0797582024,38,Morlais,Finistère,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(4,Jeuness création,,0363901524,13,Vannes,Morbihan,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(5,Génération artistique,,0454958000,58,Pontivy,Morbihan,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(6,L art de tout,,0994725156,45,Auray,Morbihan,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(7,Tout est un art,,0294036880,21,Dinan,Côtes-d Armor,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(8,Exprimez-vous,,0423291465,53,Guingamp,Côtes-d Armor,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(9,L artiste,,0759050282,33,Saint-Brieuc,Côtes-d Armor,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(10,Chapeau l artiste,,0596399806,23,Nantes,Loire Atlantique,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(11,Arts et images,,0407429702,22,Saint-Nazaire,Loire Atlantique,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(12,Arts et culture,,0295104292,15,Crossac,Loire Atlantique,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(13,Peintre à part,,0109622756,49,Angers,Maine et Loire,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(14,Arts& Crafts Gallery,,0889151680,12,Avrillé,Maine et Loire,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(15,Dream Works,,0381823914,52,Chalones sur Loire,Maine et Loire,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(16,Arts Baroques,,0968246670,16,Le Mans,Sarthe,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(17,Captivant Toiles,,0197265895,39,Sablé sur Sarthe,Sarthe,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(18,Galerie des artistes,,0446543218,60,La Flèche,Sarthe,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(19,l Académie de l Art,,0629780503,59,Avranche,Manche,Normandie);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(20,De L Art,,0824991016,29,Granville,Manche,Normandie);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(21,Chaud de l Art,,0915626309,33,Saint-Lô,Manche,Normandie);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(22,Marée Haute Galerie,,0943630460,45,Caen,Calvados,Normandie);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(23,L attaque de L Art,,0212127783,27,Bayeux,Calvados,Normandie);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(24,L Art des artistes,,0596319484,42,Falaise,Calvados,Normandie);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(25,L Art de L Expression,,0372076847,52,Alençon,Orne,Normandie);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(26,La Cabane D Art,,0661446591,39,Argentan,Orne,Normandie);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(27,le centre de dessin,,0205271010,39,La Ferté-Macé,Orne,Normandie);