INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(1,Dessines-moi,42 Cours Marechal-Joffre,0599156850,56,Quimper,Finistère,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(2,Creation en tout genre,58 Rue de Verdun,0630867315,60,Brest,Finistère,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(3,Pick and mix,32 Chemin Du Lavarin Sud,0313726853,38,Morlais,Finistère,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(4,Jeuness création,82 Rue Frédéric Chopin,0314598665,13,Vannes,Morbihan,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(5,Génération artistique,1 Avenue des Tuileries,0769421546,58,Pontivy,Morbihan,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(6,L art de tout,89 avenue Ferdinand de Lesseps,0391952187,45,Auray,Morbihan,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(7,Tout est un art,32 rue Grande Fusterie,0164083692,21,Dinan,Côtes-d Armor,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(8,Exprimez-vous,52 rue de la République,0775245586,53,Guingamp,Côtes-d Armor,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(9,L artiste,2 cours Jean Jaures,0679793430,33,Saint-Brieuc,Côtes-d Armor,Bretagne);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(10,Chapeau l artiste,7 Rue Roussy,0408931548,23,Nantes,Loire Atlantique,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(11,Arts et images,49 Faubourg Saint Honoré,0173614882,22,Saint-Nazaire,Loire Atlantique,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(12,Arts et culture,20 rue Pierre Motte,0714347423,15,Crossac,Loire Atlantique,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(13,Peintre à part,47 Rue de la Pompe,0148390470,49,Angers,Maine et Loire,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(14,Arts& Crafts Gallery,29 rue Lenotre,0589348662,12,Avrillé,Maine et Loire,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(15,Dream Works,92 Place de la Madeleine,0741495851,52,Chalones sur Loire,Maine et Loire,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(16,Arts Baroques,86 avenue de l Amandier,0151512367,16,Le Mans,Sarthe,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(17,Captivant Toiles,62 rue Petite Fusterie,0431432965,39,Sablé sur Sarthe,Sarthe,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(18,Galerie des artistes,3 Rue St Ferréol,0247751207,60,La Flèche,Sarthe,Pays de la Loire);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(19,l Académie de l Art,99 rue de Lille,0180858893,59,Avranche,Manche,Normandie);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(20,De L Art,35 avenue Jules Ferry,0643648067,29,Granville,Manche,Normandie);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(21,Chaud de l Art,95 rue Charles Corbeau,0738543636,33,Saint-Lô,Manche,Normandie);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(22,Marée Haute Galerie,36 Rue du Palais,0686496199,45,Caen,Calvados,Normandie);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(23,L attaque de L Art,67 Chemin Du Lavarin Sud,0619925107,27,Bayeux,Calvados,Normandie);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(24,L Art des artistes,27 boulevard Bryas,0307982448,42,Falaise,Calvados,Normandie);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(25,L Art de L Expression,18 Rue du Limas,0239177862,52,Alençon,Orne,Normandie);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(26,La Cabane D Art,98 rue Descartes,0438942877,39,Argentan,Orne,Normandie);
INSERT INTO Club(numClub,nomClub,adresse,numTelephone,nombreAdherent,ville,departement,region) VALUES(27,le centre de dessin,7 rue Adolphe Wurtz,0367513509,39,La Ferté-Macé,Orne,Normandie);